using System.Globalization;
using System.Text;
using Microsoft.CodeAnalysis;

namespace Plank.InternalGen;

[Generator]
public sealed class DeltaBinaryPackedInt32Generator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var hasDecoder = context.CompilationProvider.Select(static (compilation, _) =>
            compilation.Assembly.GetTypeByMetadataName(
                "Plank.Reading.Logical.Internal.DeltaBinaryPackedDecoder") is not null);

        context.RegisterSourceOutput(hasDecoder, static (sourceContext, present) =>
        {
            if (present)
                sourceContext.AddSource("DeltaBinaryPackedDecoder.FastInt32.g.cs", Generate());
        });
    }

    static string Generate()
    {
        var source = new StringBuilder(120_000);
        source.AppendLine("// Generated by DeltaBinaryPackedInt32Generator.");
        source.AppendLine("using System.Buffers.Binary;");
        source.AppendLine("using System.Runtime.CompilerServices;");
        source.AppendLine("using System.Runtime.InteropServices;");
        source.AppendLine();
        source.AppendLine("namespace Plank.Reading.Logical.Internal;");
        source.AppendLine();
        source.AppendLine("static partial class DeltaBinaryPackedDecoder");
        source.AppendLine("{");
        source.AppendLine("    static void DecodeInt32MiniBlockFast(ReadOnlySpan<byte> packed, int bitWidth, long minDelta,");
        source.AppendLine("        ref long previous, Span<int> destination)");
        source.AppendLine("    {");
        source.AppendLine("        switch (bitWidth)");
        source.AppendLine("        {");
        for (var width = 1; width <= 56; width++)
            source.Append("            case ").Append(width).Append(": DecodeInt32MiniBlockFastW")
                .Append(width).AppendLine("(packed, minDelta, ref previous, destination); return;");
        source.AppendLine("            default: throw new ArgumentOutOfRangeException(nameof(bitWidth));");
        source.AppendLine("        }");
        source.AppendLine("    }");
        source.AppendLine();

        for (var width = 1; width <= 56; width++)
        {
            var mask = "0x" + ((1UL << width) - 1).ToString("X", CultureInfo.InvariantCulture) + "UL";
            source.AppendLine("    [MethodImpl(MethodImplOptions.NoInlining | MethodImplOptions.AggressiveOptimization)]");
            source.Append("    static void DecodeInt32MiniBlockFastW").Append(width)
                .AppendLine("(ReadOnlySpan<byte> packed, long minDelta,");
            source.AppendLine("        ref long previous, Span<int> destination)");
            source.AppendLine("    {");
            source.AppendLine("        ref var source = ref MemoryMarshal.GetReference(packed);");
            source.AppendLine("        ref var target = ref MemoryMarshal.GetReference(destination);");
            source.AppendLine("        var current = previous;");
            source.AppendLine("        for (var group = 0; group < 4; group++)");
            source.AppendLine("        {");
            source.Append("            var byteOffset = group * ").Append(width).AppendLine(";");
            for (var word = 0; word < (width + 7) / 8; word++)
            {
                source.Append("            var word").Append(word)
                    .Append(" = Unsafe.ReadUnaligned<ulong>(ref Unsafe.Add(ref source, byteOffset + ")
                    .Append(word * 8).AppendLine("));");
                source.Append("            if (!BitConverter.IsLittleEndian) word").Append(word)
                    .Append(" = BinaryPrimitives.ReverseEndianness(word").Append(word).AppendLine(");");
            }

            for (var lane = 0; lane < 8; lane++)
            {
                var bit = lane * width;
                var word = bit / 64;
                var shift = bit % 64;
                var expression = shift == 0 ? "word" + word : "(word" + word + " >> " + shift + ")";
                if (shift + width > 64)
                    expression = "(" + expression + " | (word" + (word + 1) + " << " + (64 - shift) + "))";
                source.Append("            current = unchecked(current + minDelta + (long)(")
                    .Append(expression).Append(" & ").Append(mask).AppendLine("));");
                source.Append("            Unsafe.Add(ref target, group * 8 + ").Append(lane)
                    .AppendLine(") = unchecked((int)current);");
            }
            source.AppendLine("        }");
            source.AppendLine("        previous = current;");
            source.AppendLine("    }");
            source.AppendLine();
        }
        source.AppendLine("}");
        return source.ToString();
    }
}
